### ISSUE TITLE
[BUG] Salvar ordem de serviço

### ISSUE THREAD

**Issue by ellendsx** [cnmurakami/RSCAR-Automotiva#2]
**Descrição do Bug**
Ao clicar em salvar cliente, a página não está retornando a ordem de serviço aberta, continua na mesma URL, porém o cadastro está sendo efetuado com sucesso no banco. 

**Reprodução**
Passos para reproduzir o bug.
1. Ir para 'Abrir ordem' - http://127.0.0.1:5000/2000/ordem/
2. Clicar em 'Salvar'
3. Ver o bug.

**Comportamento esperado**
Ao clicar em salvar, deve retornar a página de ordem de serviço com a ordem aberta. Ex: http://127.0.0.1:5000/ordem/2009/

**Comment by ellendsx** [comment]
A aba de criar ordem não está direcionando novamente para ordem aberta.

**Comment by cnmurakami** [comment]
Não consegui reproduzir o bug. Você tentou criar ordem a partir de qual página? A URL para criação mudou para /<id_veiculo>/criar_ordem

Seguem as tentativas que fiz para reproduzir:

Caminho da página de detalhes do cliente:
![image](https://github.com/user-attachments/assets/fdee6164-ea84-4572-9958-6f8824eda1ae)

Caminho da página de detalhes do veículo:
![image](https://github.com/user-attachments/assets/3881a182-ae39-4fa9-8f0f-f83760667370)

Caminho da página de busca:
![image](https://github.com/user-attachments/assets/b4e81ddd-674a-464a-bce4-0e705b5cb2c7)

Link de criação de ordem da barra de menu/homepage: (ao pesquisar veículo, redireciona para a página de busca, mesmo print de cima)
![image](https://github.com/user-attachments/assets/0c4f5a87-24b1-4ab6-92dd-2a069e6205dd)

Página de criação que aparece depois desses 4 testes:
![image](https://github.com/user-attachments/assets/0b83c4e8-31f9-4c9d-bdd0-375be84fad40)

Ordem criada:
![image](https://github.com/user-attachments/assets/5a55d4e7-78c8-449b-ac4b-71fc39cac3b2)

Edição de ordem:
![image](https://github.com/user-attachments/assets/eafb5055-1858-4c5c-8610-d5ea0e1c220c)

Ordem salva depois de editar:
![image](https://github.com/user-attachments/assets/b2ab7dca-782e-4c57-ac3b-5c0e74a654a9)
